### ISSUE TITLE
NoSuchMethodError for swagger-core version

### ISSUE THREAD

**Issue by edwise** [Vect0rPro/dropwizard-swagger#3]
`Exception in thread "main" java.lang.NoSuchMethodError: org.hibernate.validator.HibernateValidatorConfiguration.addValueExtractor(Ljavax/validation/valueextraction/ValueExtractor;)Ljavax/validation/Configuration;
	at io.dropwizard.validation.BaseValidator.newConfiguration(BaseValidator.java:27)
	at io.dropwizard.jersey.validation.Validators.newConfiguration(Validators.java:33)
	at io.dropwizard.jersey.validation.Validators.newValidatorFactory(Validators.java:26)
	at io.dropwizard.setup.Bootstrap.<init>(Bootstrap.java:67)
	at io.dropwizard.Application.run(Application.java:86)
...`

This problem is because of this: https://github.com/dropwizard/dropwizard/issues/3089

You need to update the swagger-core version

**Comment by ravidesai47** [comment]
@edwise Can you please help me how to reproduce this issue with pom file and swagger bundle initialization part. I will try to reproduce the same and will fix it. Then I can share snapshot version with you to test the same and then we can release the new version.

**Comment by ravidesai47** [comment]
@edwise Thanks for reporting this issue. I will update swagger-core to the latest available version and release the same.

**Comment by ravidesai47** [comment]
@edwise Upgraded version `2.0.28-1` would be available on maven central after approx 4 hours from the time of this comment.

**Comment by edwise** [comment]
Thanks!! :)
